language: node_js
node_js: 10

env:
  - ELECTRON_VERSION=4
  - ELECTRON_VERSION=5

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
      - ELECTRON_CACHE=$HOME/.cache/electron
    - os: linux
      sudo: required
      dist: trusty
      before_install:
      - sudo apt-get update
      - sudo apt-get install -y libxtst-dev libx11-dev libxrender-dev libxkbfile-dev
      env:
      - ELECTRON_CACHE=$HOME/.cache/electron

cache:
  directories:
  - $HOME/.cache/electron

before_script:
  - 'if [ "ELECTRON_VERSION" ]; then npm install --no-package-lock electron@^$ELECTRON_VERSION.0.0; fi'
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; sleep 3

script:
- npm run ci
